version: "3"
services:
  zaproxy:
    image: owasp/zap2docker-stable
    container_name: zaproxy
    command: [
      "zap-x.sh",
      "-daemon",
      "-host", "0.0.0.0", "-port", "8098",
      "-config", "api.disablekey=true",
      "-config", "api.addrs.addr.name=.*",
      "-config", "api.addrs.addr.regex=true"
    ]
#    ports:
#      - "127.0.0.1:8098:8098"
    volumes:
      - data:/data
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: '16000M'
#        reservations:
#          cpus: '0.25'
#          memory: '8000M'
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '4000M'
        reservations:
          cpus: '0.25'
          memory: '2000M'
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '4000M'
        reservations:
          cpus: '0.25'
          memory: '2000M'
  zapphireye:
    container_name: zapphireye
    image: zapphireye
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
     - SPRING_DATA_MONGODB_HOST=mongodb
    #restart: always
volumes:
  data: {}